### ISSUE TITLE
Add tox support

### ISSUE THREAD

**Issue by hugorodgerbrown** [yunojuno/poetry-template#1]

**Comment by stevejalim** [comment]
Is this now resolved, given https://github.com/yunojuno/poetry-template/blob/master/tox.ini ? Looks like it might be - thanks! ✅

**Comment by hugorodgerbrown** [comment]
Yup - it is. It's ugly though - poetry doesn't really support build matrix configurations, so you have to duplicate dependencies in the tox file itself.

**Comment by hugorodgerbrown** [comment]
See https://github.com/yunojuno/poetry-template/blob/master/tox.ini#L5-L15 - this is duplicating deps defined in poetry.lock
